version: '3.9'

services:
  2048-app1:
    container_name: 2048-app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - ./:/app
  2048-app2:
    container_name: 2048-app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    volumes:
      - ./:/app